language: python
matrix:
  include:
   - python: "3.6"
   - os: osx
     language: generic
     osx_image: xcode7.3
     env:
      - PYENV_VERSION='3.6.5'
      - PYTHON_CONFIGURE_OPTS="--enable-framework"

before_install:
 - |
     if [[ -n "$PYENV_VERSION" ]]; then
       wget https://github.com/praekeltfoundation/travis-pyenv/releases/download/0.4.0/setup-pyenv.sh
       source setup-pyenv.sh
     fi
 - pip3 install poetry pyinstaller

install:
 - "make build"

script:
 - "make typecheck"
 - "make test"
 - "make package"
