language: node_js
dist: bionic
node_js:
 - "8"
 - "node"

before_install:
 - "pyenv global 3.7"
 - "python3 -V"
 - "pip3 install git+https://github.com/ActivityWatch/aw-core.git"
 - "pip3 install git+https://github.com/ActivityWatch/aw-server.git"

install:
 - "make build"

script:
 - "make test"
