language: node_js
node_js:
 - "12"
 - "node"

cache:
  directories:
  - "$HOME/.npm"

matrix:
  allow_failures:
   - node_js: "node"

install:
 - "make install"

script:
 - "make test"
 - "make build"
