dist: xenial
language: python
matrix:
  include:
  - python: "3.6"
    services:
     - xvfb
  - os: osx
    language: generic
    env: PYENV_VERSION='3.6.5' PYTHON_CONFIGURE_OPTS="--enable-framework"

before_install:
 - |
     if [[ -n "$PYENV_VERSION" ]]; then
       wget https://github.com/praekeltfoundation/travis-pyenv/releases/download/0.4.0/setup-pyenv.sh
       source setup-pyenv.sh
     fi
   # We might want to move this into the integration test script
 - |
     if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then
       # Workaround for issue with Qt integration test on xenial: https://github.com/pytest-dev/pytest-qt/issues/266#issuecomment-510035926
       sudo apt-get install -y libdbus-1-3 libxkbcommon-x11-0;
     fi
 - python3 -V
 - pip3 -V
 - pip3 install --upgrade pip poetry
 - pip3 install pyinstaller

install:
 - make build

script:
 - make typecheck
 - make test
 - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then
     make test-integration;
   fi
 - make package

